language: csharp
mono:
  - 5.10.0
solution: "./OptimizelySDK.Travis.sln"
env:
  - COVERALLS_REPO_TOKEN=sIZu1AJRbshqiquJZXu9TsS717muEKB0g
install:
  - nuget restore ./OptimizelySDK.Travis.sln
  - nuget install ./OptimizelySDK.Tests/packages.config -OutputDirectory ./packages
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory ./testrunner
script:
  - xbuild /p:Configuration=Release ./OptimizelySDK.Travis.sln
  - export LD_LIBRARY_PATH=/usr/local/lib
  - mono --profile=coverage ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe --process=Single ./OptimizelySDK.Tests/bin/Release/OptimizelySDK.Tests.dll
  - mono ./packages/coveralls.net.0.7.0/tools/csmacnz.Coveralls.exe --monocov -i ./coverage.xml --serviceName travis-ci --useRelativePaths

